server:
  port : 8081

spring:
  application:
    name: blackjack-reactive

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack

  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/blackjack
    username: blackjack
    password: blackjack123

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.r2dbc: DEBUG